In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("employees_100.csv")
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [12]:
df['department'] = df['department'].str.strip().str.lower()

In [13]:
df['department'].nunique()

6

## Grouping

In [14]:
df.groupby('city')['age'].mean()

city
Bangalore    34.375000
Chennai      29.250000
Delhi        33.923077
Hyderabad    30.526316
Kolkata      27.692308
Mumbai       27.888889
Pune         31.642857
Name: age, dtype: float64

## Aggregation Functions:
- .sum()
- .mean()
- .median()
- .min()
- .max()
- .count()
- .size()
- .std()

In [15]:
df['salary'] = df['salary'].str.replace(',', '', regex = False)
df['salary'] = pd.to_numeric(df['salary'], errors= 'coerce')
df['salary'] = df['salary'].fillna(df['salary'].median(), inplace = True)

/tmp/ipykernel_861297/1752583037.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['salary'] = df['salary'].fillna(df['salary'].median(), inplace = True)

In [17]:
df.groupby(['city', 'department'])['salary'].mean()

city       department
Bangalore  data science    72862.000000
           engineering     79164.500000
           finance         67015.750000
           hr              59591.000000
           marketing       62080.666667
Chennai    engineering     73129.000000
           finance         71889.000000
           hr              49042.500000
           marketing       59354.750000
           sales           57858.000000
Delhi      data science    76267.000000
           engineering     71663.750000
           finance         66422.000000
           hr              57844.750000
           marketing       62910.000000
           sales           66095.000000
Hyderabad  data science    78145.500000
           engineering     84870.000000
           finance         71539.000000
           hr              56659.833333
           marketing       56896.000000
           sales           57669.125000
Kolkata    data science    72303.000000
           engineering     79740.500000
           finance         58998.750000
           hr              55542.000000
           marketing       59186.000000
           sales           60015.000000
Mumbai     data science    78465.000000
           engineering     70013.750000
           finance         64112.000000
           marketing       61513.500000
           sales           52862.000000
Pune       data science    75498.000000
           engineering     70502.500000
           finance         61267.000000
           hr              54148.666667
           marketing       58481.000000
Name: salary, dtype: float64

In [18]:
df.groupby('department')[['salary', 'performance_score']].mean()

                    salary  performance_score
department
data science  76450.800000           5.700000
engineering   74038.205882           5.705882
finance       65811.833333           5.333333
hr            55756.052632           6.000000
marketing     59382.000000           5.894737
sales         59289.055556           6.555556

## Agg()

In [20]:
df.groupby('department').agg({
    "salary": ['mean', 'max'],
    "performance_score": "mean",
    "employee_id": "count"
})

                    salary          performance_score employee_id
                      mean      max              mean       count
department
data science  76450.800000  88216.0          5.700000          10
engineering   74038.205882  84870.0          5.705882          17
finance       65811.833333  80597.0          5.333333          18
hr            55756.052632  66363.0          6.000000          19
marketing     59382.000000  69499.0          5.894737          19
sales         59289.055556  68490.0          6.555556           9